<?php

declare(strict_types=1);

// pattern => [channel, carrierCode]；channel 取值 'domestic' | 'international'
// 顺序即优先级：先具体后通用；数字位数规则互斥，但必须放在字母前缀规则之后（数字单号不会匹配字母规则，反之亦然）
return [
    '/^SF\d{10,12}$/i' => ['domestic', 'sf'],
    '/^SF\d{13}$/i' => ['international', 'sf-international'], // 顺丰国际 SF+13 位（国内顺丰 10-12 位，位数互斥）
    '/^JT\d{10,15}$/i' => ['domestic', 'jt'],
    '/^YD\d{8,16}$/i' => ['domestic', 'yd'],
    '/^77\d{11}$/' => ['domestic', 'sto'], // 必须在 /^\d{13}$/ 之前，否则 77 开头 13 位数字误判为 zto
    '/^3\d{12}$/' => ['domestic', 'zjs'], // 宅急送 13 位以 3 开头（中通 13 位以 7/1/0/9 开头为主），必须在 /^\d{13}$/ 之前
    '/^32\d{10}$/' => ['domestic', 'zto-freight'], // 中通快运 12 位 32 开头；必须在 /^3\d{11}$/（purolator）与 /^\d{12}$/（uc）之前
    '/^6\d{11}$/' => ['domestic', 'dainiao'], // 丹鸟 12 位 6 开头，必须在 /^\d{12}$/ 之前
    '/^3\d{11}$/' => ['international', 'purolator'], // Purolator PIN 12 位 3 开头；32 开头落入中通快运（国内优先），33/34 等命中本规则
    '/^\d{13}$/' => ['domestic', 'zto'],
    '/^\d{12}$/' => ['domestic', 'uc'], // 优速 12 位纯数字；与 zto(13) / dhl(10) / canada-post(16) 互斥
    '/^\d{14}$/' => ['domestic', 'tiantian'], // 天天快递 14 位纯数字，与其余位数规则互斥
    '/^\d{9}$/' => ['international', 'tnt'], // TNT 9 位纯数字，与其余位数规则互斥
    '/^\d{20}$/' => ['domestic', 'suning'], // 苏宁 20 位纯数字，与其余位数规则互斥
    '/^YT\d{10,12}$/i' => ['domestic', 'yto'],
    '/^YT\d{13,14}$/i' => ['international', 'yunexpress'], // 云途 YT+13/14 位；10-12 位已被 yto 规则截获
    '/^JD0\d{15}$/i' => ['international', 'yodel'], // 必须在京东规则之前（Yodel JD0 开头 16 位数字同时匹配 /^JD[A-Z0-9]{8,18}$/i）
    '/^JD[A-Z0-9]{8,18}$/i' => ['domestic', 'jd'],
    '/^CA\d{9,12}$/i' => ['domestic', 'cainiao'],
    '/^YMD\d{9,14}$/i' => ['domestic', 'ymd'],
    '/^SJ\d{10}$/i' => ['domestic', 'sxjd'], // 顺心捷达 SJ 开头 10 位
    '/^[KB]\d{11}$/i' => ['domestic', 'cre'], // 中铁快运 K/B 开头 12 位
    '/^E[A-Z]\d{9}CN$/i' => ['domestic', 'ems'], // 必须在通用 FedEx 规则之前（EA...CN 同时匹配 /^[A-Z]{2}\d{9}[A-Z]{2}$/i）
    '/^R[A-Z]\d{9}CN$/i' => ['domestic', 'china-post'], // 中国邮政国际小包挂号（RA...CN），同上需在通用 FedEx 规则之前
    '/^HT\d{10,14}$/i' => ['domestic', 'ht'],
    '/^DPK\d{8,12}$/i' => ['domestic', 'debon'],
    '/^DB\d{8,14}$/i' => ['domestic', 'debon'],
    '/^KY\d{8,14}$/i' => ['domestic', 'ky'],
    '/^ANE\d{8,14}$/i' => ['domestic', 'ane'],
    '/^DHL\d{10,15}$/i' => ['international', 'dhl'],
    '/^1Z[0-9A-Z]{16}$/i' => ['international', 'ups'],
    '/^LP\d{14,20}$/i' => ['international', 'cainiao-intl'], // 菜鸟国际 LP 开头
    '/^4PX\d{10,15}$/i' => ['international', 'fourpx'],
    '/^TV\d{14}$/i' => ['international', 'evri'], // Evri(Hermes) TV 开头 14 位
    '/^KK\d{10,12}[A-Z]{2}$/i' => ['international', 'kerry'], // 嘉里（泰国/东南亚）KK 开头
    '/^[CD]1\d{13}$/i' => ['international', 'ontrac'], // ONTRAC C/D 开头 15 位（C1 + 13 位数字）
    // 各国邮政 S10 挂号格式（XX + 9 位 + 国家码），全部必须在通用 FedEx 规则之前
    '/^[A-Z]{2}\d{9}GB$/i' => ['international', 'royal-mail'], // 必须在通用 FedEx 规则之前（XX...GB 同时匹配 /^[A-Z]{2}\d{9}[A-Z]{2}$/i）
    '/^[A-Z]{2}\d{9}JP$/i' => ['international', 'japan-post'], // 同上
    '/^[A-Z]{2}\d{9}BR$/i' => ['international', 'correios'], // 巴西邮政，同上
    '/^[A-Z]{2}\d{9}HK$/i' => ['international', 'hong-kong-post'], // 香港邮政，同上
    '/^[A-Z]{2}\d{9}KR$/i' => ['international', 'korea-post'], // 韩国邮政，同上
    '/^[A-Z]{2}\d{9}FR$/i' => ['international', 'la-poste'], // 法国邮政，同上
    '/^[A-Z]{2}\d{9}NZ$/i' => ['international', 'nz-post'], // 新西兰邮政，同上
    '/^[A-Z]{2}\d{9}IT$/i' => ['international', 'poste-italiane'], // 意大利邮政，同上
    '/^[A-Z]{2}\d{9}RU$/i' => ['international', 'russia-post'], // 俄罗斯邮政，同上
    '/^[A-Z]{2}\d{9}SG$/i' => ['international', 'singapore-post'], // 新加坡邮政，同上
    '/^[A-Z]{2}\d{9}CH$/i' => ['international', 'swiss-post'], // 瑞士邮政，同上
    '/^[A-Z]{2}\d{9}BE$/i' => ['international', 'bpost'], // 比利时邮政，同上
    '/^[A-Z]{2}\d{9}ES$/i' => ['international', 'correos'], // 西班牙邮政，同上
    '/^[A-Z]{2}\d{9}AT$/i' => ['international', 'austrian-post'], // 奥地利邮政，同上
    '/^[A-Z]{2}\d{9}NO$/i' => ['international', 'bring'], // 挪威 Bring，同上
    '/^[A-Z]{2}\d{9}TH$/i' => ['international', 'thailand-post'], // 泰国邮政，同上
    '/^[A-Z]{2}\d{9}TW$/i' => ['international', 'chunghwa-post'], // 中华邮政（台湾），同上
    '/^[A-Z]{2}\d{9}EE$/i' => ['international', 'omniva'], // 爱沙尼亚 Omniva，同上
    '/^[A-Z]{2}\d{9}FI$/i' => ['international', 'posti'], // 芬兰 Posti，同上
    '/^[A-Z]{2}\d{9}(SE|DK)$/i' => ['international', 'postnord'], // 瑞典/丹麦 PostNord，同上
    '/^[A-Z]{2}\d{9}PT$/i' => ['international', 'ctt'], // 葡萄牙 CTT，同上
    '/^[A-Z]{2}\d{9}IE$/i' => ['international', 'an-post'], // 爱尔兰 An Post，同上
    '/^[A-Z]{2}\d{9}PL$/i' => ['international', 'poczta-polska'], // 波兰 Poczta Polska，同上
    '/^[A-Z]{2}\d{9}IN$/i' => ['international', 'india-post'], // 印度 India Post，同上
    '/^[A-Z]{2}\d{9}MY$/i' => ['international', 'pos-malaysia'], // 马来西亚 Pos Malaysia，同上
    '/^[A-Z]{2}\d{9}AE$/i' => ['international', 'emirates-post'], // 阿联酋 Emirates Post，同上
    '/^[A-Z]{2}\d{9}HU$/i' => ['international', 'magyar-posta'], // 匈牙利 Magyar Posta，同上
    '/^[A-Z]{2}\d{9}CZ$/i' => ['international', 'ceska-posta'], // 捷克 Česká pošta，同上
    '/^[A-Z]{2}\d{9}GR$/i' => ['international', 'elta'], // 希腊 ELTA，同上
    '/^[A-Z]{2}\d{9}VN$/i' => ['international', 'viettel-post'], // 越南 Viettel Post，同上
    '/^[A-Z]{2}\d{9}UA$/i' => ['international', 'ukrposhta'], // 乌克兰 Ukrposhta，同上
    '/^[A-Z]{2}\d{9}TR$/i' => ['international', 'turkey-post'], // 土耳其 PTT，同上
    '/^[A-Z]{2}\d{9}IL$/i' => ['international', 'israel-post'], // 以色列 Israel Post，同上
    '/^[A-Z]{2}\d{9}EG$/i' => ['international', 'egypt-post'], // 埃及 Egypt Post，同上
    '/^[A-Z]{2}\d{9}SA$/i' => ['international', 'saudi-post'], // 沙特 Saudi Post，同上
    '/^[A-Z]{2}\d{9}ZA$/i' => ['international', 'south-african-post'], // 南非 South African Post，同上
    '/^[A-Z]{2}\d{9}MX$/i' => ['international', 'correos-mexico'], // 墨西哥 Correos de México，同上
    '/^[A-Z]{2}\d{9}AR$/i' => ['international', 'correo-argentino'], // 阿根廷 Correo Argentino，同上
    '/^[A-Z]{2}\d{9}CL$/i' => ['international', 'correos-chile'], // 智利 Correos de Chile，同上
    '/^[A-Z]{2}\d{9}ID$/i' => ['international', 'pos-indonesia'], // 印尼 Pos Indonesia，同上
    '/^[A-Z]{2}\d{9}PH$/i' => ['international', 'phl-post'], // 菲律宾 PHLPost，同上
    '/^[A-Z]{2}\d{9}PK$/i' => ['international', 'pakistan-post'], // 巴基斯坦 Pakistan Post，同上
    '/^[A-Z]{2}\d{9}KZ$/i' => ['international', 'kazpost'], // 哈萨克斯坦 Kazpost，同上
    '/^[A-Z]{2}\d{9}RO$/i' => ['international', 'romania-post'], // 罗马尼亚 Poșta Română，同上
    '/^[A-Z]{2}\d{9}HR$/i' => ['international', 'croatia-post'], // 克罗地亚 Hrvatska pošta，同上
    '/^[A-Z]{2}\d{9}SK$/i' => ['international', 'slovak-post'], // 斯洛伐克 Slovak Post，同上
    '/^[A-Z]{2}\d{9}SI$/i' => ['international', 'slovenia-post'], // 斯洛文尼亚 Pošta Slovenije，同上
    '/^[A-Z]{2}\d{9}RS$/i' => ['international', 'serbia-post'], // 塞尔维亚 Pošta Srbije，同上
    '/^[A-Z]{2}\d{9}BG$/i' => ['international', 'bulgaria-post'], // 保加利亚 Bulgarian Posts，同上
    '/^[A-Z]{2}\d{9}LT$/i' => ['international', 'lithuania-post'], // 立陶宛 Lietuvos paštas，同上
    '/^[A-Z]{2}\d{9}LV$/i' => ['international', 'latvia-post'], // 拉脱维亚 Latvijas Pasts，同上
    '/^[A-Z]{2}\d{9}MD$/i' => ['international', 'moldova-post'], // 摩尔多瓦 Poșta Moldovei，同上
    '/^[A-Z]{2}\d{9}AL$/i' => ['international', 'albania-post'], // 阿尔巴尼亚 Posta Shqiptare，同上
    '/^[A-Z]{2}\d{9}MT$/i' => ['international', 'malta-post'], // 马耳他 MaltaPost，同上
    '/^[A-Z]{2}\d{9}LU$/i' => ['international', 'luxembourg-post'], // 卢森堡 POST Luxembourg，同上
    '/^[A-Z]{2}\d{9}IS$/i' => ['international', 'iceland-post'], // 冰岛 Íslandspóstur，同上
    '/^[A-Z]{2}\d{9}CY$/i' => ['international', 'cyprus-post'], // 塞浦路斯 Cyprus Post，同上
    '/^[A-Z]{2}\d{9}BY$/i' => ['international', 'belarus-post'], // 白俄罗斯 Belpochta，同上
    '/^[A-Z]{2}\d{9}MK$/i' => ['international', 'macedonia-post'], // 北马其顿 Makedonska Pošta，同上
    '/^[A-Z]{2}\d{9}BA$/i' => ['international', 'bosnia-post'], // 波黑 BH Pošta，同上
    // A 欧洲剩余（15，含 NL 复用）
    '/^[A-Z]{2}\d{9}DE$/i' => ['international', 'deutsche-post'], // 德国 Deutsche Post，同上
    '/^[A-Z]{2}\d{9}ME$/i' => ['international', 'montenegro-post'], // 黑山 Montenegro Post，同上
    '/^[A-Z]{2}\d{9}AD$/i' => ['international', 'andorra-post'], // 安道尔 Andorra Post，同上
    '/^[A-Z]{2}\d{9}MC$/i' => ['international', 'monaco-post'], // 摩纳哥 La Poste Monaco，同上
    '/^[A-Z]{2}\d{9}LI$/i' => ['international', 'liechtenstein-post'], // 列支敦士登 Liechtenstein Post，同上
    '/^[A-Z]{2}\d{9}SM$/i' => ['international', 'san-marino-post'], // 圣马力诺 Poste San Marino，同上
    '/^[A-Z]{2}\d{9}VA$/i' => ['international', 'vatican-post'], // 梵蒂冈 Poste Vaticane，同上
    '/^[A-Z]{2}\d{9}GI$/i' => ['international', 'gibraltar-post'], // 直布罗陀 Royal Gibraltar Post，同上
    '/^[A-Z]{2}\d{9}JE$/i' => ['international', 'jersey-post'], // 泽西 Jersey Post，同上
    '/^[A-Z]{2}\d{9}GG$/i' => ['international', 'guernsey-post'], // 根西 Guernsey Post，同上
    '/^[A-Z]{2}\d{9}IM$/i' => ['international', 'isle-of-man-post'], // 马恩岛 Isle of Man Post，同上
    '/^[A-Z]{2}\d{9}FO$/i' => ['international', 'faroe-post'], // 法罗群岛 Posta Faroe Islands，同上
    '/^[A-Z]{2}\d{9}GL$/i' => ['international', 'greenland-post'], // 格陵兰 Post Greenland，同上
    '/^[A-Z]{2}\d{9}AX$/i' => ['international', 'aland-post'], // 奥兰群岛 Post Åland，同上
    '/^[A-Z]{2}\d{9}NL$/i' => ['international', 'postnl'], // 荷兰 PostNL（复用既有适配器），同上
    // B 拉美加勒比（21）
    '/^[A-Z]{2}\d{9}CO$/i' => ['international', 'colombia-post'], // 哥伦比亚 4-72，同上
    '/^[A-Z]{2}\d{9}PE$/i' => ['international', 'peru-post'], // 秘鲁 Serpost，同上
    '/^[A-Z]{2}\d{9}UY$/i' => ['international', 'uruguay-post'], // 乌拉圭 Correo Uruguayo，同上
    '/^[A-Z]{2}\d{9}PY$/i' => ['international', 'paraguay-post'], // 巴拉圭 Correo Paraguayo，同上
    '/^[A-Z]{2}\d{9}BO$/i' => ['international', 'bolivia-post'], // 玻利维亚 Correos de Bolivia，同上
    '/^[A-Z]{2}\d{9}EC$/i' => ['international', 'ecuador-post'], // 厄瓜多尔 Correos del Ecuador，同上
    '/^[A-Z]{2}\d{9}VE$/i' => ['international', 'venezuela-post'], // 委内瑞拉 Ipostel，同上
    '/^[A-Z]{2}\d{9}CR$/i' => ['international', 'costa-rica-post'], // 哥斯达黎加 Correos de Costa Rica，同上
    '/^[A-Z]{2}\d{9}PA$/i' => ['international', 'panama-post'], // 巴拿马 Correos de Panamá，同上
    '/^[A-Z]{2}\d{9}DO$/i' => ['international', 'dominican-post'], // 多米尼加 INPOSDOM，同上
    '/^[A-Z]{2}\d{9}GT$/i' => ['international', 'guatemala-post'], // 危地马拉 Correo de Guatemala，同上
    '/^[A-Z]{2}\d{9}HN$/i' => ['international', 'honduras-post'], // 洪都拉斯 HonduCorreo，同上
    '/^[A-Z]{2}\d{9}SV$/i' => ['international', 'el-salvador-post'], // 萨尔瓦多 Correos de El Salvador，同上
    '/^[A-Z]{2}\d{9}NI$/i' => ['international', 'nicaragua-post'], // 尼加拉瓜 Correos de Nicaragua，同上
    '/^[A-Z]{2}\d{9}CU$/i' => ['international', 'cuba-post'], // 古巴 Correos de Cuba，同上
    '/^[A-Z]{2}\d{9}JM$/i' => ['international', 'jamaica-post'], // 牙买加 Jamaica Post，同上
    '/^[A-Z]{2}\d{9}TT$/i' => ['international', 'trinidad-post'], // 特立尼达和多巴哥 TTPOST，同上
    '/^[A-Z]{2}\d{9}BB$/i' => ['international', 'barbados-post'], // 巴巴多斯 Barbados Post，同上
    '/^[A-Z]{2}\d{9}BS$/i' => ['international', 'bahamas-post'], // 巴哈马 Bahamas Post，同上
    '/^[A-Z]{2}\d{9}SR$/i' => ['international', 'suriname-post'], // 苏里南 Suriname Post，同上
    '/^[A-Z]{2}\d{9}GY$/i' => ['international', 'guyana-post'], // 圭亚那 Guyana Post，同上
    // C 非洲中东（21）
    '/^[A-Z]{2}\d{9}MA$/i' => ['international', 'morocco-post'], // 摩洛哥 Barid Al-Maghrib，同上
    '/^[A-Z]{2}\d{9}DZ$/i' => ['international', 'algeria-post'], // 阿尔及利亚 Algérie Poste，同上
    '/^[A-Z]{2}\d{9}TN$/i' => ['international', 'tunisia-post'], // 突尼斯 La Poste Tunisienne，同上
    '/^[A-Z]{2}\d{9}KE$/i' => ['international', 'kenya-post'], // 肯尼亚 Posta Kenya，同上
    '/^[A-Z]{2}\d{9}NG$/i' => ['international', 'nigeria-post'], // 尼日利亚 NIPOST，同上
    '/^[A-Z]{2}\d{9}ET$/i' => ['international', 'ethiopia-post'], // 埃塞俄比亚 Ethiopia Post，同上
    '/^[A-Z]{2}\d{9}GH$/i' => ['international', 'ghana-post'], // 加纳 Ghana Post，同上
    '/^[A-Z]{2}\d{9}TZ$/i' => ['international', 'tanzania-post'], // 坦桑尼亚 Tanzania Post，同上
    '/^[A-Z]{2}\d{9}UG$/i' => ['international', 'uganda-post'], // 乌干达 Uganda Post，同上
    '/^[A-Z]{2}\d{9}RW$/i' => ['international', 'rwanda-post'], // 卢旺达 Rwanda Post，同上
    '/^[A-Z]{2}\d{9}ZM$/i' => ['international', 'zambia-post'], // 赞比亚 Zampost，同上
    '/^[A-Z]{2}\d{9}ZW$/i' => ['international', 'zimbabwe-post'], // 津巴布韦 Zimpost，同上
    '/^[A-Z]{2}\d{9}MZ$/i' => ['international', 'mozambique-post'], // 莫桑比克 Mozambique Post，同上
    '/^[A-Z]{2}\d{9}AO$/i' => ['international', 'angola-post'], // 安哥拉 Correios de Angola，同上
    '/^[A-Z]{2}\d{9}SN$/i' => ['international', 'senegal-post'], // 塞内加尔 La Poste Sénégalaise，同上
    '/^[A-Z]{2}\d{9}CI$/i' => ['international', 'ivory-coast-post'], // 科特迪瓦 La Poste de Côte d'Ivoire，同上
    '/^[A-Z]{2}\d{9}CM$/i' => ['international', 'cameroon-post'], // 喀麦隆 Cameroon Post，同上
    '/^[A-Z]{2}\d{9}MU$/i' => ['international', 'mauritius-post'], // 毛里求斯 Mauritius Post，同上
    '/^[A-Z]{2}\d{9}QA$/i' => ['international', 'qatar-post'], // 卡塔尔 Qatar Post，同上
    '/^[A-Z]{2}\d{9}KW$/i' => ['international', 'kuwait-post'], // 科威特 Kuwait Post，同上
    '/^[A-Z]{2}\d{9}BH$/i' => ['international', 'bahrain-post'], // 巴林 Bahrain Post，同上
    // D 亚太剩余（21）
    '/^[A-Z]{2}\d{9}BD$/i' => ['international', 'bangladesh-post'], // 孟加拉 Bangladesh Post，同上
    '/^[A-Z]{2}\d{9}NP$/i' => ['international', 'nepal-post'], // 尼泊尔 Nepal Post，同上
    '/^[A-Z]{2}\d{9}LK$/i' => ['international', 'sri-lanka-post'], // 斯里兰卡 Sri Lanka Post，同上
    '/^[A-Z]{2}\d{9}MM$/i' => ['international', 'myanmar-post'], // 缅甸 Myanmar Post，同上
    '/^[A-Z]{2}\d{9}KH$/i' => ['international', 'cambodia-post'], // 柬埔寨 Cambodia Post，同上
    '/^[A-Z]{2}\d{9}LA$/i' => ['international', 'laos-post'], // 老挝 Laos Post，同上
    '/^[A-Z]{2}\d{9}MN$/i' => ['international', 'mongolia-post'], // 蒙古 Mongolia Post，同上
    '/^[A-Z]{2}\d{9}GE$/i' => ['international', 'georgia-post'], // 格鲁吉亚 Georgian Post，同上
    '/^[A-Z]{2}\d{9}AZ$/i' => ['international', 'azerbaijan-post'], // 阿塞拜疆 Azərpoçt，同上
    '/^[A-Z]{2}\d{9}AM$/i' => ['international', 'armenia-post'], // 亚美尼亚 HayPost，同上
    '/^[A-Z]{2}\d{9}UZ$/i' => ['international', 'uzbekistan-post'], // 乌兹别克斯坦 Uzbekistan Post，同上
    '/^[A-Z]{2}\d{9}KG$/i' => ['international', 'kyrgyzstan-post'], // 吉尔吉斯斯坦 Kyrgyz Post，同上
    '/^[A-Z]{2}\d{9}TJ$/i' => ['international', 'tajikistan-post'], // 塔吉克斯坦 Tajikistan Post，同上
    '/^[A-Z]{2}\d{9}TM$/i' => ['international', 'turkmenistan-post'], // 土库曼斯坦 Turkmenistan Post，同上
    '/^[A-Z]{2}\d{9}AF$/i' => ['international', 'afghanistan-post'], // 阿富汗 Afghanistan Post，同上
    '/^[A-Z]{2}\d{9}BT$/i' => ['international', 'bhutan-post'], // 不丹 Bhutan Post，同上
    '/^[A-Z]{2}\d{9}MV$/i' => ['international', 'maldives-post'], // 马尔代夫 Maldives Post，同上
    '/^[A-Z]{2}\d{9}BN$/i' => ['international', 'brunei-post'], // 文莱 Brunei Post，同上
    '/^[A-Z]{2}\d{9}PG$/i' => ['international', 'papua-post'], // 巴布亚新几内亚 Papua New Guinea Post，同上
    '/^[A-Z]{2}\d{9}FJ$/i' => ['international', 'fiji-post'], // 斐济 Fiji Post，同上
    '/^[A-Z]{2}\d{9}WS$/i' => ['international', 'samoa-post'], // 萨摩亚 Samoa Post，同上
    '/^[A-Z]{2}\d{9}(YP|YW|YE|YL)$/i' => ['international', 'yanwen'], // 燕文 S10 形态（YP 等尾码），同上
    '/^[A-Z]{2}\d{9}[A-Z]{2}$/i' => ['international', 'fedex'],
    '/^AUP\d{8,12}$/i' => ['international', 'australia-post'],
    '/^JJFI\d{16}$/i' => ['international', 'posti'], // 芬兰 Posti JJFI 前缀 20 位；与 JD/JT 前缀互斥
    '/^3S[A-Z0-9]{11,13}$/i' => ['international', 'postnl'],
    '/^\d{15}$/' => ['international', 'delhivery'], // 纯 15 位数字（与 9/10/12/13/14/16/20 位规则互斥）
    '/^\d{16}$/' => ['international', 'canada-post'], // 纯 16 位数字（zto 13 位规则已在前，无冲突）
    '/^\d{24}$/' => ['international', 'inpost'], // 纯 24 位数字（InPost 波兰包裹柜，新增位数，现有最长 20 位）
    '/^FEDEX\d{10,15}$/i' => ['international', 'fedex'],
    '/^GM\d{9}$/i' => ['international', 'dhl'],
    '/^LH\d{10,12}$/i' => ['international', 'dhl'],
    '/^94\d{16,22}$/' => ['international', 'usps'],
    '/^(?!77)\d{10}$/' => ['international', 'dhl'], // 纯 10 位数字 DHL 国际单号；负向断言排除 77 开头（国内旧式申通单号，10 位），避免误查 DHL API，77 开头 10 位落入 CarrierNotFoundException
];
