<?php

declare(strict_types=1);

// pattern => [channel, carrierCode]；channel 取值 'domestic' | 'international'
// 顺序即优先级：先具体后通用；数字位数规则互斥，但必须放在字母前缀规则之后（数字单号不会匹配字母规则，反之亦然）
return [
    '/^SF\d{10,12}$/i' => ['domestic', 'sf'],
    '/^SF\d{13}$/i' => ['international', 'sf-international'], // 顺丰国际 SF+13 位（国内顺丰 10-12 位，位数互斥）
    '/^JT\d{10,15}$/i' => ['domestic', 'jt'],
    '/^YD\d{8,16}$/i' => ['domestic', 'yd'],
    '/^77\d{11}$/' => ['domestic', 'sto'], // 必须在 /^\d{13}$/ 之前，否则 77 开头 13 位数字误判为 zto
    '/^3\d{12}$/' => ['domestic', 'zjs'], // 宅急送 13 位以 3 开头（中通 13 位以 7/1/0/9 开头为主），必须在 /^\d{13}$/ 之前
    '/^32\d{10}$/' => ['domestic', 'zto-freight'], // 中通快运 12 位 32 开头；必须在 /^3\d{11}$/（purolator）与 /^\d{12}$/（uc）之前
    '/^6\d{11}$/' => ['domestic', 'dainiao'], // 丹鸟 12 位 6 开头，必须在 /^\d{12}$/ 之前
    '/^3\d{11}$/' => ['international', 'purolator'], // Purolator PIN 12 位 3 开头；32 开头落入中通快运（国内优先），33/34 等命中本规则
    '/^\d{13}$/' => ['domestic', 'zto'],
    '/^\d{12}$/' => ['domestic', 'uc'], // 优速 12 位纯数字；与 zto(13) / dhl(10) / canada-post(16) 互斥
    '/^\d{14}$/' => ['domestic', 'tiantian'], // 天天快递 14 位纯数字，与其余位数规则互斥
    '/^\d{9}$/' => ['international', 'tnt'], // TNT 9 位纯数字，与其余位数规则互斥
    '/^\d{20}$/' => ['domestic', 'suning'], // 苏宁 20 位纯数字，与其余位数规则互斥
    '/^YT\d{10,12}$/i' => ['domestic', 'yto'],
    '/^YT\d{13,14}$/i' => ['international', 'yunexpress'], // 云途 YT+13/14 位；10-12 位已被 yto 规则截获
    '/^JD0\d{15}$/i' => ['international', 'yodel'], // 必须在京东规则之前（Yodel JD0 开头 16 位数字同时匹配 /^JD[A-Z0-9]{8,18}$/i）
    '/^JD[A-Z0-9]{8,18}$/i' => ['domestic', 'jd'],
    '/^CA\d{9,12}$/i' => ['domestic', 'cainiao'],
    '/^YMD\d{9,14}$/i' => ['domestic', 'ymd'],
    '/^SJ\d{10}$/i' => ['domestic', 'sxjd'], // 顺心捷达 SJ 开头 10 位
    '/^[KB]\d{11}$/i' => ['domestic', 'cre'], // 中铁快运 K/B 开头 12 位
    '/^E[A-Z]\d{9}CN$/i' => ['domestic', 'ems'], // 必须在通用 FedEx 规则之前（EA...CN 同时匹配 /^[A-Z]{2}\d{9}[A-Z]{2}$/i）
    '/^R[A-Z]\d{9}CN$/i' => ['domestic', 'china-post'], // 中国邮政国际小包挂号（RA...CN），同上需在通用 FedEx 规则之前
    '/^HT\d{10,14}$/i' => ['domestic', 'ht'],
    '/^DPK\d{8,12}$/i' => ['domestic', 'debon'],
    '/^DB\d{8,14}$/i' => ['domestic', 'debon'],
    '/^KY\d{8,14}$/i' => ['domestic', 'ky'],
    '/^ANE\d{8,14}$/i' => ['domestic', 'ane'],
    '/^DHL\d{10,15}$/i' => ['international', 'dhl'],
    '/^1Z[0-9A-Z]{16}$/i' => ['international', 'ups'],
    '/^LP\d{14,20}$/i' => ['international', 'cainiao-intl'], // 菜鸟国际 LP 开头
    '/^4PX\d{10,15}$/i' => ['international', 'fourpx'],
    '/^TV\d{14}$/i' => ['international', 'evri'], // Evri(Hermes) TV 开头 14 位
    '/^KK\d{10,12}[A-Z]{2}$/i' => ['international', 'kerry'], // 嘉里（泰国/东南亚）KK 开头
    '/^[CD]1\d{13}$/i' => ['international', 'ontrac'], // ONTRAC C/D 开头 15 位（C1 + 13 位数字）
    // 各国邮政 S10 挂号格式（XX + 9 位 + 国家码），全部必须在通用 FedEx 规则之前
    '/^[A-Z]{2}\d{9}GB$/i' => ['international', 'royal-mail'], // 必须在通用 FedEx 规则之前（XX...GB 同时匹配 /^[A-Z]{2}\d{9}[A-Z]{2}$/i）
    '/^[A-Z]{2}\d{9}JP$/i' => ['international', 'japan-post'], // 同上
    '/^[A-Z]{2}\d{9}BR$/i' => ['international', 'correios'], // 巴西邮政，同上
    '/^[A-Z]{2}\d{9}HK$/i' => ['international', 'hong-kong-post'], // 香港邮政，同上
    '/^[A-Z]{2}\d{9}KR$/i' => ['international', 'korea-post'], // 韩国邮政，同上
    '/^[A-Z]{2}\d{9}FR$/i' => ['international', 'la-poste'], // 法国邮政，同上
    '/^[A-Z]{2}\d{9}NZ$/i' => ['international', 'nz-post'], // 新西兰邮政，同上
    '/^[A-Z]{2}\d{9}IT$/i' => ['international', 'poste-italiane'], // 意大利邮政，同上
    '/^[A-Z]{2}\d{9}RU$/i' => ['international', 'russia-post'], // 俄罗斯邮政，同上
    '/^[A-Z]{2}\d{9}SG$/i' => ['international', 'singapore-post'], // 新加坡邮政，同上
    '/^[A-Z]{2}\d{9}CH$/i' => ['international', 'swiss-post'], // 瑞士邮政，同上
    '/^[A-Z]{2}\d{9}BE$/i' => ['international', 'bpost'], // 比利时邮政，同上
    '/^[A-Z]{2}\d{9}ES$/i' => ['international', 'correos'], // 西班牙邮政，同上
    '/^[A-Z]{2}\d{9}AT$/i' => ['international', 'austrian-post'], // 奥地利邮政，同上
    '/^[A-Z]{2}\d{9}NO$/i' => ['international', 'bring'], // 挪威 Bring，同上
    '/^[A-Z]{2}\d{9}TH$/i' => ['international', 'thailand-post'], // 泰国邮政，同上
    '/^[A-Z]{2}\d{9}TW$/i' => ['international', 'chunghwa-post'], // 中华邮政（台湾），同上
    '/^[A-Z]{2}\d{9}EE$/i' => ['international', 'omniva'], // 爱沙尼亚 Omniva，同上
    '/^[A-Z]{2}\d{9}FI$/i' => ['international', 'posti'], // 芬兰 Posti，同上
    '/^[A-Z]{2}\d{9}(SE|DK)$/i' => ['international', 'postnord'], // 瑞典/丹麦 PostNord，同上
    '/^[A-Z]{2}\d{9}PT$/i' => ['international', 'ctt'], // 葡萄牙 CTT，同上
    '/^[A-Z]{2}\d{9}IE$/i' => ['international', 'an-post'], // 爱尔兰 An Post，同上
    '/^[A-Z]{2}\d{9}PL$/i' => ['international', 'poczta-polska'], // 波兰 Poczta Polska，同上
    '/^[A-Z]{2}\d{9}IN$/i' => ['international', 'india-post'], // 印度 India Post，同上
    '/^[A-Z]{2}\d{9}MY$/i' => ['international', 'pos-malaysia'], // 马来西亚 Pos Malaysia，同上
    '/^[A-Z]{2}\d{9}AE$/i' => ['international', 'emirates-post'], // 阿联酋 Emirates Post，同上
    '/^[A-Z]{2}\d{9}HU$/i' => ['international', 'magyar-posta'], // 匈牙利 Magyar Posta，同上
    '/^[A-Z]{2}\d{9}CZ$/i' => ['international', 'ceska-posta'], // 捷克 Česká pošta，同上
    '/^[A-Z]{2}\d{9}GR$/i' => ['international', 'elta'], // 希腊 ELTA，同上
    '/^[A-Z]{2}\d{9}VN$/i' => ['international', 'viettel-post'], // 越南 Viettel Post，同上
    '/^[A-Z]{2}\d{9}UA$/i' => ['international', 'ukrposhta'], // 乌克兰 Ukrposhta，同上
    '/^[A-Z]{2}\d{9}TR$/i' => ['international', 'turkey-post'], // 土耳其 PTT，同上
    '/^[A-Z]{2}\d{9}IL$/i' => ['international', 'israel-post'], // 以色列 Israel Post，同上
    '/^[A-Z]{2}\d{9}EG$/i' => ['international', 'egypt-post'], // 埃及 Egypt Post，同上
    '/^[A-Z]{2}\d{9}SA$/i' => ['international', 'saudi-post'], // 沙特 Saudi Post，同上
    '/^[A-Z]{2}\d{9}ZA$/i' => ['international', 'south-african-post'], // 南非 South African Post，同上
    '/^[A-Z]{2}\d{9}MX$/i' => ['international', 'correos-mexico'], // 墨西哥 Correos de México，同上
    '/^[A-Z]{2}\d{9}AR$/i' => ['international', 'correo-argentino'], // 阿根廷 Correo Argentino，同上
    '/^[A-Z]{2}\d{9}CL$/i' => ['international', 'correos-chile'], // 智利 Correos de Chile，同上
    '/^[A-Z]{2}\d{9}ID$/i' => ['international', 'pos-indonesia'], // 印尼 Pos Indonesia，同上
    '/^[A-Z]{2}\d{9}PH$/i' => ['international', 'phl-post'], // 菲律宾 PHLPost，同上
    '/^[A-Z]{2}\d{9}PK$/i' => ['international', 'pakistan-post'], // 巴基斯坦 Pakistan Post，同上
    '/^[A-Z]{2}\d{9}KZ$/i' => ['international', 'kazpost'], // 哈萨克斯坦 Kazpost，同上
    '/^[A-Z]{2}\d{9}RO$/i' => ['international', 'romania-post'], // 罗马尼亚 Poșta Română，同上
    '/^[A-Z]{2}\d{9}HR$/i' => ['international', 'croatia-post'], // 克罗地亚 Hrvatska pošta，同上
    '/^[A-Z]{2}\d{9}SK$/i' => ['international', 'slovak-post'], // 斯洛伐克 Slovak Post，同上
    '/^[A-Z]{2}\d{9}SI$/i' => ['international', 'slovenia-post'], // 斯洛文尼亚 Pošta Slovenije，同上
    '/^[A-Z]{2}\d{9}RS$/i' => ['international', 'serbia-post'], // 塞尔维亚 Pošta Srbije，同上
    '/^[A-Z]{2}\d{9}BG$/i' => ['international', 'bulgaria-post'], // 保加利亚 Bulgarian Posts，同上
    '/^[A-Z]{2}\d{9}LT$/i' => ['international', 'lithuania-post'], // 立陶宛 Lietuvos paštas，同上
    '/^[A-Z]{2}\d{9}LV$/i' => ['international', 'latvia-post'], // 拉脱维亚 Latvijas Pasts，同上
    '/^[A-Z]{2}\d{9}MD$/i' => ['international', 'moldova-post'], // 摩尔多瓦 Poșta Moldovei，同上
    '/^[A-Z]{2}\d{9}AL$/i' => ['international', 'albania-post'], // 阿尔巴尼亚 Posta Shqiptare，同上
    '/^[A-Z]{2}\d{9}MT$/i' => ['international', 'malta-post'], // 马耳他 MaltaPost，同上
    '/^[A-Z]{2}\d{9}LU$/i' => ['international', 'luxembourg-post'], // 卢森堡 POST Luxembourg，同上
    '/^[A-Z]{2}\d{9}IS$/i' => ['international', 'iceland-post'], // 冰岛 Íslandspóstur，同上
    '/^[A-Z]{2}\d{9}CY$/i' => ['international', 'cyprus-post'], // 塞浦路斯 Cyprus Post，同上
    '/^[A-Z]{2}\d{9}BY$/i' => ['international', 'belarus-post'], // 白俄罗斯 Belpochta，同上
    '/^[A-Z]{2}\d{9}MK$/i' => ['international', 'macedonia-post'], // 北马其顿 Makedonska Pošta，同上
    '/^[A-Z]{2}\d{9}BA$/i' => ['international', 'bosnia-post'], // 波黑 BH Pošta，同上
    '/^[A-Z]{2}\d{9}(YP|YW|YE|YL)$/i' => ['international', 'yanwen'], // 燕文 S10 形态（YP 等尾码），同上
    '/^[A-Z]{2}\d{9}[A-Z]{2}$/i' => ['international', 'fedex'],
    '/^AUP\d{8,12}$/i' => ['international', 'australia-post'],
    '/^JJFI\d{16}$/i' => ['international', 'posti'], // 芬兰 Posti JJFI 前缀 20 位；与 JD/JT 前缀互斥
    '/^3S[A-Z0-9]{11,13}$/i' => ['international', 'postnl'],
    '/^\d{15}$/' => ['international', 'delhivery'], // 纯 15 位数字（与 9/10/12/13/14/16/20 位规则互斥）
    '/^\d{16}$/' => ['international', 'canada-post'], // 纯 16 位数字（zto 13 位规则已在前，无冲突）
    '/^\d{24}$/' => ['international', 'inpost'], // 纯 24 位数字（InPost 波兰包裹柜，新增位数，现有最长 20 位）
    '/^FEDEX\d{10,15}$/i' => ['international', 'fedex'],
    '/^GM\d{9}$/i' => ['international', 'dhl'],
    '/^LH\d{10,12}$/i' => ['international', 'dhl'],
    '/^94\d{16,22}$/' => ['international', 'usps'],
    '/^(?!77)\d{10}$/' => ['international', 'dhl'], // 纯 10 位数字 DHL 国际单号；负向断言排除 77 开头（国内旧式申通单号，10 位），避免误查 DHL API，77 开头 10 位落入 CarrierNotFoundException
];
